### ISSUE TITLE
Database schema 

### ISSUE THREAD

**Issue by someyaaltous** [Survival-DEV/golden-lines#3]

**Comment by bayan-404** [comment]
DRAWIO LINK : https://app.diagrams.net/#HSurvival-DEV%2Fgolden-lines%2Fmain%2FUntitled%20Diagram.drawio


![Untitled Diagram](https://user-images.githubusercontent.com/57558867/105174834-cdd5e300-5b2b-11eb-853e-f3a1ae9c52c0.png)
